/** Allowed class audience values. Clients must send 2–5 of each list. */

export const PERFECT_FOR_OPTIONS = [
  'Flexibility & Mobility',
  'Strength & Stability',
  'Balance & Coordination',
  'Better Posture',
  'Stress Management',
  'Relaxation',
  'Mindfulness',
  'Mental Clarity',
  'Better Focus',
  'Better Sleep',
  'Breath Awareness',
  'Body Awareness',
  'Healthy Movement',
  'Building a Regular Practice',
  'Gentle Practice',
  'Active Practice',
  'Deep Rest',
];

export const NOT_SUITABLE_IF_OPTIONS = [
  'Complete Beginners',
  'Advanced Practice Required',
  'High-Intensity Practice Not Recommended',
  'Acute Injury',
  'Severe Pain',
  'Recent Surgery',
  'Significant Mobility Limitations',
  'Dizziness / Vertigo',
  'Breathing Difficulties',
  'Pregnancy',
  'Post-Surgery Recovery',
  'Medical Condition Requiring Professional Supervision',
  'Physical Activity Restricted by Doctor',
  'Unable to Participate Safely Without Assistance',
];

export const WHAT_YOU_GAIN_OPTIONS = [
  'Improved Flexibility',
  'Improved Mobility',
  'Improved Strength',
  'Improved Stability',
  'Improved Balance',
  'Better Posture',
  'Better Coordination',
  'Improved Body Awareness',
  'Improved Movement',
  'Increased Physical Ease',
  'Stress Relief',
  'Relaxation',
  'Mental Clarity',
  'Better Focus',
  'Mindfulness',
  'Emotional Relaxation',
  'Sense of Calm',
  'Improved Self-Awareness',
  'Better Breath Awareness',
  'Improved Breathing Practice',
  'Greater Mindfulness',
  'Improved Concentration',
  'Deeper Relaxation',
  'Inner Calm',
  'Rest & Recovery',
  'Deep Rest',
  'Relaxation Support',
  'Better Sleep Routine',
  'Recovery & Restoration',
  'Reduced Mental Tension',
];
